export const genreIcons: Record<string, string> = {
  "Action": "🎮",
  "RPG": "⚔️",
  "Strategy": "🎯",
  "Sports": "⚽",
  "Adventure": "🗺️",
  "Horror": "👻",
  "Shooter": "🎯",
  "Racing": "🏎️",
  "Puzzle": "🧩",
  "Arcade": "👾",
  "Simulation": "🎮",
  "Fighting": "🥊",
  "Platformer": "🏃",
  "MMO": "🌐",
  "Indie": "🎨",
};

export const genreTranslations: Record<string, string> = {
  "Action": "Action",
  "RPG": "RPG",
  "Strategy": "Stratégie",
  "Sports": "Sport",
  "Adventure": "Aventure",
  "Horror": "Horreur",
  "Shooter": "FPS",
  "Racing": "Course",
  "Puzzle": "Réflexion",
  "Arcade": "Arcade",
  "Simulation": "Simulation",
  "Fighting": "Combat",
  "Platformer": "Plateforme",
  "MMO": "MMO",
  "Indie": "Indépendant",
}; 